version: "3"

tasks:
  init:
    cmds:
      - echo "service initialize..."
      - source env/bin/activate
      - pip install -r requirements.txt
    silent: true

  save:
    cmds:
      - echo "run pip freeze..."
      - pip freeze > requirements.txt
    silent: true

  run:
    cmds:
      - echo "detector starting..."
      - python main.py
    silent: true
