version: "3"

tasks:
  init:
    cmds:
      - echo "service initialize..."
      - python -m venv env
      - source env/bin/activate
      - pip install -r requirements.txt
    silent: true

  save:
    cmds:
      - echo "run pip freeze..."
      - pip freeze > requirements.txt
    silent: true

  run:
    cmds:
      - echo "detector starting..."
      - python main.py
    silent: true

  gen:
    cmds:
      - echo "generate requirements.txt..."
      - pipreqs --force .
    silent: true

  gen-gitignore:
    cmds:
      - echo "generate .gitignore..."
      - touch .gitignore
      - echo "*env/" >> .gitignore
      - echo ".vscode/" >> .gitignore
      - echo ".idea/" >> .gitignore
      - echo "__pycache__/" >> .gitignore
      - echo ".DS_Store" >> .gitignore
    silent: true
